export const GET_LIST_CINEMA = "GET_LIST_CINEMA";
export const GET_DETAIL_FILM = "GET_DETAIL_FILM";

export const GET_LICH_CHIEU = "GET_LICH_CHIEU";

export const GET_MA_LICH_CHIEU = "GET_MA_LICH_CHIEU";
